
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Leren1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CategoryHeader
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CategoryHeader()
    {

        this.ArticleHeaders = new HashSet<ArticleHeader>();

    }


    public string CategoryID { get; set; }

    public string SubjectID { get; set; }

    public string CategoryTitle { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArticleHeader> ArticleHeaders { get; set; }

    public virtual SubjectHeader SubjectHeader { get; set; }

}

}
