
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Leren1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubjectHeader
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubjectHeader()
    {

        this.ArticleHeaders = new HashSet<ArticleHeader>();

        this.CategoryHeaders = new HashSet<CategoryHeader>();

    }


    public string SubjectID { get; set; }

    public string SubjectTitle { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArticleHeader> ArticleHeaders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CategoryHeader> CategoryHeaders { get; set; }

}

}
