
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Leren1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.ArticleHeaders = new HashSet<ArticleHeader>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int Phone_number { get; set; }

    public System.DateTime DOB { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArticleHeader> ArticleHeaders { get; set; }

}

}
